define({
    titleDialog: 'Deploy',
    noContent: 'This project has no deployed apps. Please click the \'Create New Deploy\' button.',
    messageFailCallAPI: 'Failed to call Webida API.',
    messageSuccessEdit: 'Successfully edited the app information.',
    messageCancelEdit: 'Canceled editing the app information.',
    messageFailEdit: 'Failed to edit the app information.',
    messageInformSelectFiles: 'Select Files to Deploy',
    messageSuccessSelectFiles: 'Files to deploy were selected successfully.',
    messageCancelSelectFiles: 'Canceled file selection.',
    messageFailSelectFiles: 'Failed to select files to deploy.',
    validationNoNameOrDomain: 'Enter a name and a domain.',
    titleDeleteAppDialog: 'Delete Deployed App',
    contentDeleteAppDialog: 'Are you sure to delete this deployed app?',
    messageSuccessDeleteApp: 'Successfully deleted the deployed app.',
    messageCancelDeleteApp: 'Canceled to delete the deployed app.',
    messageInformProgressDeploy: 'Deploying...',
    messageSuccessDeploy: '\'${appId}\' was successfully deployed',
    messageFailDeploy: 'Failed to deploy the app.',
    messageSuccessStartApp: 'Successfully started the deployed app.',
    messageSuccessStopApp: 'Successfully stopped the deployed app.',
    messageAvailable: 'Available',
    messageNotAvailable: 'This domain is not available.',
    validationNoName: 'Enter a name.',
    validationNameContainSpaces: 'Names cannot contain spaces.',
    validationNameExist: 'This name already exists in the project.',
    messageFailCheckDomain: 'Failed to receive a deploy domain.',
    validationNoDomain: 'Enter a deploy project domain postfix.',
    messageError: 'Unknown app status',
    titleContentArea: 'App Information',
    titleLeaveDialog: 'Leave This Page?',
    contentLeaveDialog: 'Any unsaved change(s) will be lost. Are you sure?',
    labelName: 'Name',
    labelSubDomain: 'Subdomain',
    labelStatus: 'Status',
    labelUrl: 'URL',
    labelDescription: 'Desc.',
    validationInvalidArgument: 'Error: Argument is invalid (ex>project=fsid/workspace/project)',
    messageFailGetUserInfo: 'get userinfo fail',
    'menuDeplo&y': 'Deploy',
    messageFailGetProjects: 'Failed to get the project list.',
    messageNoProject: 'No projects in workspace.'
});
