define({
    root: {
        fileMenuCloseOthers: 'Cl&ose Others',
        fileMenuCloseAll: 'C&lose All',
        fileMenuSave: '&Save',
        editMenuUndo: '&Undo',
        editMenuRedo: '&Redo',
        editMenuDelete: '&Delete',
        editMenuSelectAll: 'Select &All',
        editMenuSelectLine: 'Select L&ine',
        editMenuLine: '&Line',
        editMenuLineIndent: '&Indent',
        editMenuLineDedent: '&Dedent',
        editMenuLineMoveLineUp: 'Move Line U&p',
        editMenuLineMoveLineDown: 'Move Line Dow&n',
        editMenuLineDeleteLines: 'D&elete Lines',
        editMenuSource: '&Source',
        editMenuSourceFold: '&Fold',
        editMenuSourceToggleLineComments: '&Toggle Line Comments',
        editMenuSourceToggleBlockComment: 'Toggle Block Comment',
        editMenuSourceCommentOutSelection: 'Comment out selection',
        editMenuSourceBeautify: '&Beautify',
        editMenuSourceBeautifyAll: 'B&eautify All',
        editMenuSourceRenameVariables: '&Rename Variables',
        editMenuLineMoveCursorLineToMiddle: 'Move Cursor Line to Middle',
        editMenuLineMoveCursorLineToTop: 'Move Cursor Line to Top',
        editMenuLineMoveCursorLineToBottom: 'Move Cursor Line to Bottom',
        navMenuGotoDefinition: '&Go to Definition',
        navMenuGotoLine: 'G&o to Line',
        navMenuGotoMatchingBrace: 'Go to &Matching Brace',
    },
    'en-us': true
});

