define({
    contextMenuCloseOthers: 'Cl&ose Others',
    contextMenuCloseAll: 'C&lose All',
    contextMenuUndo: '&Undo',
    contextMenuRedo: '&Redo',
    contextMenuSave: '&Save',
    contextMenuDelete: '&Delete',
    contextMenuSelectAll: 'Select &All',
    contextMenuSelectLine: 'Select L&ine',
    contextMenuLineIndent: '&Indent',
    contextMenuLineDedent: '&Dedent',
    contextMenuLineMoveLineUp: 'Move Line U&p',
    contextMenuLineMoveLineDown: 'Move Line Dow&n',
    contextMenuLineDeleteLines: 'D&elete Lines',
    contextMenuLineMoveCursorLineToMiddle: 'Move Cursor Line to Middle',
    contextMenuLineMoveCursorLineToTop: 'Move Cursor Line to Top',
    contextMenuLineMoveCursorLineToBottom: 'Move Cursor Line to Bottom',
    contextMenuLine: '&Line',
    contextMenuGotoLine: 'G&o to Line',
    contextMenuGotoMatchingBrace: 'Go to &Matching Brace',
    editMenuUndo: '&Undo',
    editMenuRedo: '&Redo',
    editMenuDelete: '&Delete',
    editMenuSelectAll: 'Select &All',
    editMenuSelectLine: 'Select L&ine',
    editMenuLineIndent: '&Indent',
    editMenuLineDedent: '&Dedent',
    editMenuLineMoveLineUp: 'Move Line U&p',
    editMenuLineMoveLineDown: 'Move Line Dow&n',
    editMenuLineDeleteLines: 'D&elete Lines',
    editMenuLine: '&Line',
    editMenuSourceFold: '&Fold',
    editMenuSource: '&Source',
    preferenceGroupTheme: 'Theme',
    preferenceItemEditorTheme: 'Editor theme',
    preferenceGroupFont: 'Font',
    preferenceItemEditorFontSize: 'Editor font size',
    preferenceItemEditorFont: 'Editor font',
    preferenceGroupEditorConfig: 'Editor Config',
    preferenceItemUseEditorconfigFiles: 'Use .editorconfig files',
    preferenceGroupCommon: 'Common',
    preferenceItemTrimTrailingWhiteSpaceBeforeSaving: 'Trim trailing white-space before saving',
    preferenceItemInsertFinalNewLineBeforeSaving: 'Insert final new-line before saving',
    preferenceItemReplaceTabsInIndentaionsBeforeSaving: 'Replace tabs in indentations before saving',
    preferenceItemWrapLines: 'Wrap lines',
    preferenceGroupIndent: 'Indent',
    preferenceItemTabSize: 'Tab size',
    preferenceItemIndentUnit: 'Indent unit',
    preferenceItemUseIndentsWithTabs: 'Use indents with tabs',
    preferenceItemIndentLinesOnPaste: 'Indent lines on paste',
    preferenceItemEditorKeyMap: 'Editor key map',
    preferenceItemShowWhitespaceCharacters: 'Show whitespace characters',
    preferenceItemShowLineNumbers: 'Show line numbers'
});

