define({
    pluginHasInconsistentKey: 'This plug-in has a duplicate or inconsistent key: ${key}',
    pluginHasInconsistentCommandHierarchy: 'This plug-in has an inconsistent command hierarchy at ${key}',
    invalidSpecificationOfItems: 'Invalid specification of items at key ${key} in the plug-in',
    find: 'Find',
    cancel: 'Cancel',
    go: 'Go',
    findInFiles: 'Find in Files',
    enterPatternToFind: 'Enter the pattern to find.',
    enterDirToSearch: 'Enter the directory to search.',
    searchFilesFailure: 'Failed to search files.',
    selectDirectory: 'Select a Directory',
    valueRequired: 'A value is required',
    noSuchFile: 'No such file.',
    noSuchFileAs: '${filename}: No such file.',
    goToFile: 'Go to File',
    loadingError: 'Loading error...',
    loadingProgress: 'Loading ${progress}',
    atLine: 'at line',
    selectTargetDir: 'Select a target directory',
    enterSubstringOfFilePath: 'Enter a substring of the file path.',
    searchFilesDesc: 'Fill in the following form to search files for a keyword.',
    requiredFields: 'Required fields',
    keywordToFind: 'Keyword to find',
    asARegularExpression: 'as a regular expression',
    baseDirToSearch: 'Base directory to search',
    browse: 'Browse',
    optionalFields: 'Optional fields',
    ignoreCase: 'Ignore case',
    wholeWordsOnly: 'Whole words only',
    excludedDirs: 'Excluded directories',
    searchedFiles: 'Searched files',
    selectAFileToGo: 'Select a file to go :',
    loading: 'Loading...',
    target: 'Target :',
    browse3Dot: 'Browse...',
    uploadDropZoneDesc: 'Select files and/or directories to upload by dropping them to the following zone.',
    dropThemHere: 'Drop them here',
    or: 'or',
    selectFiles: 'Select files',
    selectFilesAndDirs: 'Selected files and directories:',
    filesDirs: '-Files , Directories',
    size: '-Size',
    selectOrClearAll: 'Select/Clear All',
    targetDir: 'Target directory:',
    nameIs: 'Name:',
    typeIs: 'Type:',
    locationIs: 'Location:',
    sizeIs: 'Size:',
    contentsIs: 'Contents:',
    updateAttrIs: 'Update (attributes):',
    updateContentIs: 'Update (content):',
    accessIs: 'Access:',
    matchedFile: 'Matched File',
    resultOfFindingPattern: '# Result of finding pattern ${pattern} in files within a directory ${path}'
});
