define({
    labelAsteriskExplain: 'indicates required field',
    labelName: 'Name',
    labelProject: 'Project',
    labelPath: 'Path',
    labelQueryString: 'Query String (?)',
    labelHash: 'Hash (#)',
    labelWindowFeatures: 'Window Features',
    labelLiveReload: 'Live Reload',
    labelApply: 'Apply',
    messageFailOpenWindow: 'Window can\'t be opened. It might be interrupted by pop-up blocking, please check it.',
    messageNotFoundImplementation: '${delegatorType} hasn\'t be implemented at run configurator type(${type})',
    messageRunDelegator: 'Run delegator',
    messageDebugDelegator: 'Debug delegator',
    messageSuccessRun: 'Run configuration \'${project}:${name}\' was successfully launched',
    messageSuccessDebug: 'Debug configuration \'${project}:${name}\' was successfully launched',
    messageSuccessSave: 'Run configuration \'${project}:${name}\' was successfully saved',
    messageSuccessRemove: 'Run configuration \'${project}:${name}\' was successfully saved',
    validationNoName: 'You should fill the configuration name',
    validationNoProject: 'You should fill the target project',
    valueNewConfiguration: 'New configuration',
    labelMoreRunConfigurations: 'Run Configurations...',
    labelMoreDebugConfigurations: 'Debug Configurations...',
    labelLatestRun: ' [latest run]',
    labelNoProjectIndex: 'No project index',
    validationNoContextPath: 'No valid context path',
    validationPreventWorkspaceRun: 'Cannot run workspace directory',
    messageNoRunConfiguration: 'Cannot find a run configuration. Add a new one.',
    messageNoDebugConfiguration: 'Cannot find a debug configuration. Add a new one.',
    messageNotExist: '${target} is not exist.',
    labelGeneralWebApplication: 'General Web Application',
    titleRunConfiguration: 'Run Configurations',
    titleDebugConfiguration: 'Debug Configurations',
    labelRunConfiguration: 'Run',
    labelDebugConfiguration: 'Debug',
    labelClose: 'Close',
    messageConfirmCloseDialog: '${title} was ${unSaveMsg}. Are you sure you want to close this dialog?',
    messageConfirmDeleteConfiguration: 'Are you sure you want to delete this configuration?',
    messageFailSaveConfiguration: 'not be saved',
    titleDeleteDialog: 'Delete ${title}',
    messageCancelDelete: 'Deletion is canceled',
    messageConfirmClose: 'You will may lose unsaved data. Are you sure to continue?',
    messageFailFindRoot: 'Cannot find root path',
    titleSelectMain: 'Select the Main File to Run',
    validationNoSelectedFile: 'Select a file.',
    validationNoPath: 'Select a path',
    validationInvalidQueryString: 'Invalid query string',
    messageFailGetProjects: 'failed to get project list',
    'menu&Run': '&Run',
    'menuRun &with': 'Run &with',
    menuDebug: 'Debug',
    'menuDebug with': 'Debug with'
});
