define({
    labelApply: 'Apply',
    labelAsteriskExplain: 'indicates required field',
    labelClose: 'Close',
    labelDebugConfiguration: 'Debug',
    labelGeneralWebApplication: 'General Web Application',
    labelHash: 'Hash (#)',
    labelLatestRun: ' [latest run]',
    labelLiveReload: 'Live Reload',
    labelMoreDebugConfigurations: 'Debug Configurations...',
    labelMoreRunConfigurations: 'Run Configurations...',
    labelName: 'Name',
    labelNoProjectIndex: 'No project index',
    labelPath: 'Path',
    labelProject: 'Project',
    labelQueryString: 'Query String (?)',
    labelRunConfiguration: 'Run',
    labelSelectProject: '-- SELECT PROJECT --',
    labelWindowFeatures: 'Window Features',
    'menu&Run': '&Run',
    'menuDebug with': 'Debug with',
    menuDebug: 'Debug',
    'menuRun &with': 'Run &with',
    messageCancelDelete: 'Deletion is canceled',
    messageConfirmClose: 'You will may lose unsaved data. Are you sure to continue?',
    messageConfirmCloseDialog: '${title} was ${unSaveMsg}. Are you sure you want to close this dialog?',
    messageConfirmDeleteConfiguration: 'Are you sure you want to delete this configuration?',
    messageDebugDelegator: 'Debug delegator',
    messageFailFindRoot: 'Cannot find root path',
    messageFailGetProjects: 'failed to get project list',
    messageFailOpenWindow: 'Window can\'t be opened. It might be interrupted by pop-up blocking, please check it.',
    messageFailSaveConfiguration: 'not be saved',
    messageNoDebugConfiguration: 'Cannot find a debug configuration. Add a new one.',
    messageNoRunConfiguration: 'Cannot find a run configuration. Add a new one.',
    messageNotExist: '${target} is not exist.',
    messageNotFoundImplementation: '${delegatorType} hasn\'t be implemented at run configurator type(${type})',
    messageRunDelegator: 'Run delegator',
    messageSuccessDebug: 'Debug configuration \'${project}:${name}\' was successfully launched',
    messageSuccessRemove: 'Run configuration \'${project}:${name}\' was successfully saved',
    messageSuccessRun: 'Run configuration \'${project}:${name}\' was successfully launched',
    messageSuccessSave: 'Run configuration \'${project}:${name}\' was successfully saved',
    titleDebugConfiguration: 'Debug Configurations',
    titleDeleteDialog: 'Delete ${title}',
    titleRunConfiguration: 'Run Configurations',
    titleSelectMain: 'Select the Main File to Run',
    validationInvalidForm: 'Form contains invalid data. Please correct first.',
    validationInvalidQueryString: 'Invalid query string',
    validationNoContextPath: 'No valid context path',
    validationNoName: 'You should fill the configuration name',
    validationNoPath: 'Select a path',
    validationNoProject: 'You should fill the target project',
    validationNoSelectedFile: 'Select a file.',
    validationPreventWorkspaceRun: 'Cannot run workspace directory',
    valueNewConfiguration: 'New configuration'
});
